export const MyProjectsData = [
  {
    id: 1,
    picture_source: "../Assets/MyProjects/MadeByNyland.jpeg",
    header_text: "MadeByNyland",
    paragraph_text: "My Portfolio Website that you're currently using.",
    url: "https://MadebyNy.land",
  },
  {
    id: 2,
    picture_source: "../Assets/MyProjects/ValcanoEscape.jpeg",
    header_text: "Volcano Escape VR",
    paragraph_text: "Virtual Reality final project, Can You escape in time?",
    url: "https://youtu.be/2ItmzyDFm3Y",
  },
  {
    id: 3,
    picture_source: "../Assets/MyProjects/Edison.jpeg",
    header_text: "GE Project Edison",
    paragraph_text:
      "Hackathon entry, webapp w/ chatbot & VR experience inside.",
    url: "https://github.com/Nyland-Sidifall/GELightBulb",
  },
  {
    id: 4,
    picture_source: "../Assets/MyProjects/TheKickbackFilm.jpeg",
    header_text: "The Kickback Film",
    paragraph_text: "A website for a film set around a college party setting.",
    url: "https://github.com/Nyland-Sidifall/TheKickbackFilm",
  },
  {
    id: 1,
    picture_source: "../Assets/MyProjects/MadeByNyland.jpeg",
    header_text: "MadeByNyland",
    paragraph_text: "My Portfolio Website that you're currently using.",
    url: "https://MadebyNy.land",
  },
  {
    id: 2,
    picture_source: "../Assets/MyProjects/ValcanoEscape.jpeg",
    header_text: "Volcano Escape VR",
    paragraph_text: "Virtual Reality final project, Can You escape in time?",
    url: "https://youtu.be/2ItmzyDFm3Y",
  },
  {
    id: 3,
    picture_source: "../Assets/MyProjects/Edison.jpeg",
    header_text: "GE Project Edison",
    paragraph_text:
      "Hackathon entry, webapp w/ chatbot & VR experience inside.",
    url: "https://github.com/Nyland-Sidifall/GELightBulb",
  },
  {
    id: 4,
    picture_source: "../Assets/MyProjects/TheKickbackFilm.jpeg",
    header_text: "The Kickback Film",
    paragraph_text: "A website for a film set around a college party setting.",
    url: "https://github.com/Nyland-Sidifall/TheKickbackFilm",
  },
  {
    id: 1,
    picture_source: "../Assets/MyProjects/MadeByNyland.jpeg",
    header_text: "MadeByNyland",
    paragraph_text: "My Portfolio Website that you're currently using.",
    url: "https://MadebyNy.land",
  },
  {
    id: 2,
    picture_source: "../Assets/MyProjects/ValcanoEscape.jpeg",
    header_text: "Volcano Escape VR",
    paragraph_text: "Virtual Reality final project, Can You escape in time?",
    url: "https://youtu.be/2ItmzyDFm3Y",
  },
  {
    id: 3,
    picture_source: "../Assets/MyProjects/Edison.jpeg",
    header_text: "GE Project Edison",
    paragraph_text:
      "Hackathon entry, webapp w/ chatbot & VR experience inside.",
    url: "https://github.com/Nyland-Sidifall/GELightBulb",
  },
  {
    id: 4,
    picture_source: "../Assets/MyProjects/TheKickbackFilm.jpeg",
    header_text: "The Kickback Film",
    paragraph_text: "A website for a film set around a college party setting.",
    url: "https://github.com/Nyland-Sidifall/TheKickbackFilm",
  },
  {
    id: 1,
    picture_source: "../Assets/MyProjects/MadeByNyland.jpeg",
    header_text: "MadeByNyland",
    paragraph_text: "My Portfolio Website that you're currently using.",
    url: "https://MadebyNy.land",
  },
  {
    id: 2,
    picture_source: "../Assets/MyProjects/ValcanoEscape.jpeg",
    header_text: "Volcano Escape VR",
    paragraph_text: "Virtual Reality final project, Can You escape in time?",
    url: "https://youtu.be/2ItmzyDFm3Y",
  },
  {
    id: 3,
    picture_source: "../Assets/MyProjects/Edison.jpeg",
    header_text: "GE Project Edison",
    paragraph_text:
      "Hackathon entry, webapp w/ chatbot & VR experience inside.",
    url: "https://github.com/Nyland-Sidifall/GELightBulb",
  },
  {
    id: 4,
    picture_source: "../Assets/MyProjects/TheKickbackFilm.jpeg",
    header_text: "The Kickback Film",
    paragraph_text: "A website for a film set around a college party setting.",
    url: "https://github.com/Nyland-Sidifall/TheKickbackFilm",
  },
  {
    id: 1,
    picture_source: "../Assets/MyProjects/MadeByNyland.jpeg",
    header_text: "MadeByNyland",
    paragraph_text: "My Portfolio Website that you're currently using.",
    url: "https://MadebyNy.land",
  },
  {
    id: 2,
    picture_source: "../Assets/MyProjects/ValcanoEscape.jpeg",
    header_text: "Volcano Escape VR",
    paragraph_text: "Virtual Reality final project, Can You escape in time?",
    url: "https://youtu.be/2ItmzyDFm3Y",
  },
  {
    id: 3,
    picture_source: "../Assets/MyProjects/Edison.jpeg",
    header_text: "GE Project Edison",
    paragraph_text:
      "Hackathon entry, webapp w/ chatbot & VR experience inside.",
    url: "https://github.com/Nyland-Sidifall/GELightBulb",
  },
  {
    id: 4,
    picture_source: "../Assets/MyProjects/TheKickbackFilm.jpeg",
    header_text: "The Kickback Film",
    paragraph_text: "A website for a film set around a college party setting.",
    url: "https://github.com/Nyland-Sidifall/TheKickbackFilm",
  },
];
